// User-agent tokens of AI crawlers, AI search indexers and AI "on behalf of a
// user" fetchers. Used both as robots.txt groups and as a hard block in proxy.ts.
// Ordinary search engines (Googlebot, Bingbot) and link-preview bots
// (facebookexternalhit, Twitterbot, Slackbot, ...) are intentionally not listed.
export const AI_BOTS: string[] = [
  // OpenAI
  "GPTBot",
  "ChatGPT-User",
  "ChatGPT Agent",
  "OAI-SearchBot",
  "OAI-AdsBot",
  // Anthropic
  "ClaudeBot",
  "Claude-User",
  "Claude-SearchBot",
  "Claude-Web",
  "anthropic-ai",
  // Google (Google-Extended is a robots.txt-only token with no user agent)
  "Google-Extended",
  "Google-CloudVertexBot",
  "GoogleOther",
  "Gemini-Deep-Research",
  "NotebookLM",
  "GoogleAgent-Mariner",
  "GoogleAgent-URLContext",
  // Apple (robots.txt-only token)
  "Applebot-Extended",
  // Perplexity
  "PerplexityBot",
  "Perplexity-User",
  // Meta
  "meta-externalagent",
  "meta-externalfetcher",
  "meta-webindexer",
  "FacebookBot",
  // Amazon
  "Amazonbot",
  "Amzn-SearchBot",
  "Amzn-User",
  "bedrockbot",
  // Microsoft / Mistral / Cohere / DeepSeek / xAI-adjacent
  "MistralAI-User",
  "MistralAI-Index",
  "MistralAI-Training",
  "cohere-ai",
  "cohere-training-data-crawler",
  "DeepSeekBot",
  // ByteDance / Chinese LLM vendors
  "Bytespider",
  "TikTokSpider",
  "DoubaoBot",
  "QwenBot",
  "TongyiBot",
  "KimiBot",
  "Kimi-SearchBot",
  "Kimi-User",
  "ERNIEBot",
  "YiyanBot",
  "ChatGLM-Spider",
  "PanguBot",
  "PetalBot",
  // Training-set / dataset crawlers
  "CCBot",
  "AI2Bot",
  "Ai2Bot-Dolma",
  "img2dataset",
  "omgili",
  "Webzio-Extended",
  "Timpibot",
  "VelenPublicWebCrawler",
  "Brightbot",
  "Crawlspace",
  "ImagesiftBot",
  "Diffbot",
  "ICC-Crawler",
  "Kangaroo Bot",
  "Sidetrade indexer bot",
  "SemrushBot-OCOB",
  "SemrushBot-SWA",
  "Scrapy",
  // AI answer engines / agent fetchers
  "DuckAssistBot",
  "YouBot",
  "PhindBot",
  "Andibot",
  "iaskspider",
  "iAskBot",
  "ExaBot",
  "ExaSearchBot",
  "TavilyBot",
  "LinkupBot",
  "FirecrawlAgent",
  "Crawl4AI",
];
